"""Secret-detection rules ported from gitleaks. GENERATED — do not edit.

Regenerate with scripts/port_gitleaks_rules.py
Source: https://raw.githubusercontent.com/gitleaks/gitleaks/master/config/gitleaks.toml @ 09242ce9c8a6
Ported: 2026-09-09

gitleaks is MIT licensed, Copyright (c) 2019 Zachary Rice.
https://github.com/gitleaks/gitleaks — see NOTICE for the full licence.
"""

RULES = [{'id': '1password-secret-key',
  'keywords': ['a3-'],
  'regex': '\\bA3-[A-Z0-9]{6}-(?:(?:[A-Z0-9]{11})|(?:[A-Z0-9]{6}-[A-Z0-9]{5}))-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\\b',
  'entropy': 3.8,
  'secret_group': None},
 {'id': '1password-service-account-token',
  'keywords': ['ops_'],
  'regex': 'ops_eyJ[a-zA-Z0-9+/]{250,}={0,3}',
  'entropy': 4,
  'secret_group': None},
 {'id': 'adafruit-api-key',
  'keywords': ['adafruit'],
  'regex': '(?i)[\\w.-]{0,50}?(?:adafruit)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'adobe-client-id',
  'keywords': ['adobe'],
  'regex': '(?i)[\\w.-]{0,50}?(?:adobe)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'adobe-client-secret',
  'keywords': ['p8e-'],
  'regex': '(?i)\\b(p8e-[a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'age-secret-key',
  'keywords': ['age-secret-key-1'],
  'regex': 'AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}',
  'entropy': None,
  'secret_group': None},
 {'id': 'airtable-api-key',
  'keywords': ['airtable'],
  'regex': '(?i)[\\w.-]{0,50}?(?:airtable)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{17})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'airtable-personnal-access-token',
  'keywords': ['airtable'],
  'regex': '\\b(pat[[:alnum:]]{14}\\.[a-f0-9]{64})\\b',
  'entropy': None,
  'secret_group': None},
 {'id': 'algolia-api-key',
  'keywords': ['algolia'],
  'regex': '(?i)[\\w.-]{0,50}?(?:algolia)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'alibaba-access-key-id',
  'keywords': ['ltai'],
  'regex': '(?i)\\b(LTAI[a-z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'alibaba-secret-key',
  'keywords': ['alibaba'],
  'regex': '(?i)[\\w.-]{0,50}?(?:alibaba)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'anthropic-admin-api-key',
  'keywords': ['sk-ant-admin01'],
  'regex': '\\b(sk-ant-admin01-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'anthropic-api-key',
  'keywords': ['sk-ant-api03'],
  'regex': '\\b(sk-ant-api03-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'artifactory-api-key',
  'keywords': ['akcp'],
  'regex': '\\bAKCp[A-Za-z0-9]{69}\\b',
  'entropy': 4.5,
  'secret_group': None},
 {'id': 'artifactory-reference-token',
  'keywords': ['cmvmd'],
  'regex': '\\bcmVmd[A-Za-z0-9]{59}\\b',
  'entropy': 4.5,
  'secret_group': None},
 {'id': 'asana-client-id',
  'keywords': ['asana'],
  'regex': '(?i)[\\w.-]{0,50}?(?:asana)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'asana-client-secret',
  'keywords': ['asana'],
  'regex': '(?i)[\\w.-]{0,50}?(?:asana)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'atlassian-api-token',
  'keywords': ['atlassian', 'confluence', 'jira', 'atatt3'],
  'regex': '(?i)[\\w.-]{0,50}?(?:(?-i:ATLASSIAN|[Aa]tlassian)|(?-i:CONFLUENCE|[Cc]onfluence)|(?-i:JIRA|[Jj]ira))(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{20}[a-f0-9]{4})(?:[\\x60\'"\\s;]|\\\\[nr]|$)|\\b(ATATT3[A-Za-z0-9_\\-=]{186})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3.5,
  'secret_group': None},
 {'id': 'authress-service-client-access-key',
  'keywords': ['sc_', 'ext_', 'scauth_', 'authress_'],
  'regex': '(?i)\\b((?:sc|ext|scauth|authress)_[a-z0-9]{5,30}\\.[a-z0-9]{4,6}\\.(?-i:acc)[_-][a-z0-9-]{10,32}\\.[a-z0-9+/_=-]{30,120})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'aws-access-token',
  'keywords': ['a3t', 'akia', 'asia', 'abia', 'acca'],
  'regex': '\\b((?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16})\\b',
  'entropy': 3,
  'secret_group': None},
 {'id': 'aws-amazon-bedrock-api-key-long-lived',
  'keywords': ['absk'],
  'regex': '\\b(ABSK[A-Za-z0-9+/]{109,269}={0,2})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'aws-amazon-bedrock-api-key-short-lived',
  'keywords': ['bedrock-api-key-'],
  'regex': 'bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29t',
  'entropy': 3,
  'secret_group': None},
 {'id': 'azure-ad-client-secret',
  'keywords': ['q~'],
  'regex': '(?:^|[\\\\\'"\\x60\\s>=:(,)])([a-zA-Z0-9_~.]{3}\\dQ~[a-zA-Z0-9_~.-]{31,34})(?:$|[\\\\\'"\\x60\\s<),])',
  'entropy': 3,
  'secret_group': None},
 {'id': 'beamer-api-token',
  'keywords': ['beamer'],
  'regex': '(?i)[\\w.-]{0,50}?(?:beamer)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(b_[a-z0-9=_\\-]{44})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'bitbucket-client-id',
  'keywords': ['bitbucket'],
  'regex': '(?i)[\\w.-]{0,50}?(?:bitbucket)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'bitbucket-client-secret',
  'keywords': ['bitbucket'],
  'regex': '(?i)[\\w.-]{0,50}?(?:bitbucket)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'bittrex-access-key',
  'keywords': ['bittrex'],
  'regex': '(?i)[\\w.-]{0,50}?(?:bittrex)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'bittrex-secret-key',
  'keywords': ['bittrex'],
  'regex': '(?i)[\\w.-]{0,50}?(?:bittrex)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'cisco-meraki-api-key',
  'keywords': ['meraki'],
  'regex': '[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:(?-i:[Mm]eraki|MERAKI))(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'clickhouse-cloud-api-secret-key',
  'keywords': ['4b1d'],
  'regex': '\\b(4b1d[A-Za-z0-9]{38})\\b',
  'entropy': 3,
  'secret_group': None},
 {'id': 'clojars-api-token',
  'keywords': ['clojars_'],
  'regex': '(?i)CLOJARS_[a-z0-9]{60}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'cloudflare-api-key',
  'keywords': ['cloudflare'],
  'regex': '(?i)[\\w.-]{0,50}?(?:cloudflare)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'cloudflare-global-api-key',
  'keywords': ['cloudflare'],
  'regex': '(?i)[\\w.-]{0,50}?(?:cloudflare)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{37})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'cloudflare-origin-ca-key',
  'keywords': ['cloudflare', 'v1.0-'],
  'regex': '\\b(v1\\.0-[a-f0-9]{24}-[a-f0-9]{146})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'codecov-access-token',
  'keywords': ['codecov'],
  'regex': '(?i)[\\w.-]{0,50}?(?:codecov)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'cohere-api-token',
  'keywords': ['cohere', 'co_api_key'],
  'regex': '[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:cohere|CO_API_KEY)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-zA-Z0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'coinbase-access-token',
  'keywords': ['coinbase'],
  'regex': '(?i)[\\w.-]{0,50}?(?:coinbase)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'confluent-access-token',
  'keywords': ['confluent'],
  'regex': '(?i)[\\w.-]{0,50}?(?:confluent)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'confluent-secret-key',
  'keywords': ['confluent'],
  'regex': '(?i)[\\w.-]{0,50}?(?:confluent)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'contentful-delivery-api-token',
  'keywords': ['contentful'],
  'regex': '(?i)[\\w.-]{0,50}?(?:contentful)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{43})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'curl-auth-header',
  'keywords': ['curl'],
  'regex': '(?i)\\bcurl\\b(?:.*?|.*?(?:[\\r\\n]{1,2}.*?){1,5})[ \\t\\n\\r](?:-H|--header)(?:=|[ '
           '\\t]{0,5})(?:"(?:Authorization:[ \\t]{0,5}(?:Basic[ '
           '\\t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ '
           '\\t]([\\w=~@.+/-]{8,})|([\\w=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ '
           '\\t]{0,5}([\\w=~@.+/-]{8,}))"|\'(?:Authorization:[ \\t]{0,5}(?:Basic[ '
           '\\t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ '
           '\\t]([\\w=~@.+/-]{8,})|([\\w=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ '
           "\\t]{0,5}([\\w=~@.+/-]{8,}))')(?:\\B|\\s|\\z)",
  'entropy': 2.75,
  'secret_group': None},
 {'id': 'curl-auth-user',
  'keywords': ['curl'],
  'regex': '\\bcurl\\b(?:.*|.*(?:[\\r\\n]{1,2}.*){1,5})[ \\t\\n\\r](?:-u|--user)(?:=|[ '
           '\\t]{0,5})("(:[^"]{3,}|[^:"]{3,}:|[^:"]{3,}:[^"]{3,})"|\'([^:\']{3,}:[^\']{3,})\'|((?:"[^"]{3,}"|\'[^\']{3,}\'|[\\w$@.-]+):(?:"[^"]{3,}"|\'[^\']{3,}\'|[\\w${}@.-]+)))(?:\\s|\\z)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'databricks-api-token',
  'keywords': ['dapi'],
  'regex': '\\b(dapi[a-f0-9]{32}(?:-\\d)?)(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'datadog-access-token',
  'keywords': ['datadog'],
  'regex': '(?i)[\\w.-]{0,50}?(?:datadog)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'defined-networking-api-token',
  'keywords': ['dnkey'],
  'regex': '(?i)[\\w.-]{0,50}?(?:dnkey)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(dnkey-[a-z0-9=_\\-]{26}-[a-z0-9=_\\-]{52})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'digitalocean-access-token',
  'keywords': ['doo_v1_'],
  'regex': '\\b(doo_v1_[a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'digitalocean-pat',
  'keywords': ['dop_v1_'],
  'regex': '\\b(dop_v1_[a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'digitalocean-refresh-token',
  'keywords': ['dor_v1_'],
  'regex': '(?i)\\b(dor_v1_[a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'discord-api-token',
  'keywords': ['discord'],
  'regex': '(?i)[\\w.-]{0,50}?(?:discord)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'discord-client-id',
  'keywords': ['discord'],
  'regex': '(?i)[\\w.-]{0,50}?(?:discord)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9]{18})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'discord-client-secret',
  'keywords': ['discord'],
  'regex': '(?i)[\\w.-]{0,50}?(?:discord)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'doppler-api-token',
  'keywords': ['dp.pt.'],
  'regex': '(?i)dp\\.pt\\.[a-z0-9]{43}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'droneci-access-token',
  'keywords': ['droneci'],
  'regex': '(?i)[\\w.-]{0,50}?(?:droneci)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'dropbox-api-token',
  'keywords': ['dropbox'],
  'regex': '(?i)[\\w.-]{0,50}?(?:dropbox)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{15})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'dropbox-long-lived-api-token',
  'keywords': ['dropbox'],
  'regex': '(?i)[\\w.-]{0,50}?(?:dropbox)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\\-_=]{43})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'dropbox-short-lived-api-token',
  'keywords': ['dropbox'],
  'regex': '(?i)[\\w.-]{0,50}?(?:dropbox)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(sl\\.[a-z0-9\\-=_]{135})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'duffel-api-token',
  'keywords': ['duffel_'],
  'regex': '(?i)duffel_(?:test|live)_[a-z0-9_\\-=]{43}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'dynatrace-api-token',
  'keywords': ['dt0c01.'],
  'regex': '(?i)dt0c01\\.[a-z0-9]{24}\\.[a-z0-9]{64}',
  'entropy': 4,
  'secret_group': None},
 {'id': 'easypost-api-token',
  'keywords': ['ezak'],
  'regex': '(?i)\\bEZAK[a-z0-9]{54}\\b',
  'entropy': 2,
  'secret_group': None},
 {'id': 'easypost-test-api-token',
  'keywords': ['eztk'],
  'regex': '(?i)\\bEZTK[a-z0-9]{54}\\b',
  'entropy': 2,
  'secret_group': None},
 {'id': 'etsy-access-token',
  'keywords': ['etsy'],
  'regex': '(?i)[\\w.-]{0,50}?(?:(?-i:ETSY|[Ee]tsy))(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'facebook-access-token',
  'keywords': ['facebook'],
  'regex': '(?i)\\b(\\d{15,16}(\\||%)[0-9a-z\\-_]{27,40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'facebook-page-access-token',
  'keywords': ['eaam', 'eaac'],
  'regex': '(?i)\\b(EAA[MC][a-z0-9]{100,})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'facebook-secret',
  'keywords': ['facebook'],
  'regex': '(?i)[\\w.-]{0,50}?(?:facebook)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'fastly-api-token',
  'keywords': ['fastly'],
  'regex': '(?i)[\\w.-]{0,50}?(?:fastly)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'finicity-api-token',
  'keywords': ['finicity'],
  'regex': '(?i)[\\w.-]{0,50}?(?:finicity)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'finicity-client-secret',
  'keywords': ['finicity'],
  'regex': '(?i)[\\w.-]{0,50}?(?:finicity)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'finnhub-access-token',
  'keywords': ['finnhub'],
  'regex': '(?i)[\\w.-]{0,50}?(?:finnhub)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'flickr-access-token',
  'keywords': ['flickr'],
  'regex': '(?i)[\\w.-]{0,50}?(?:flickr)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'flutterwave-encryption-key',
  'keywords': ['flwseck_test'],
  'regex': '(?i)FLWSECK_TEST-[a-h0-9]{12}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'flutterwave-public-key',
  'keywords': ['flwpubk_test'],
  'regex': '(?i)FLWPUBK_TEST-[a-h0-9]{32}-X',
  'entropy': 2,
  'secret_group': None},
 {'id': 'flutterwave-secret-key',
  'keywords': ['flwseck_test'],
  'regex': '(?i)FLWSECK_TEST-[a-h0-9]{32}-X',
  'entropy': 2,
  'secret_group': None},
 {'id': 'flyio-access-token',
  'keywords': ['fo1_', 'fm1', 'fm2_'],
  'regex': '\\b((?:fo1_[\\w-]{43}|fm1[ar]_[a-zA-Z0-9+\\/]{100,}={0,3}|fm2_[a-zA-Z0-9+\\/]{100,}={0,3}))(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'frameio-api-token',
  'keywords': ['fio-u-'],
  'regex': '(?i)fio-u-[a-z0-9\\-_=]{64}',
  'entropy': None,
  'secret_group': None},
 {'id': 'freemius-secret-key',
  'keywords': ['secret_key'],
  'regex': '(?i)["\']secret_key["\']\\s*=>\\s*["\'](sk_[\\S]{29})["\']',
  'entropy': None,
  'secret_group': None},
 {'id': 'freshbooks-access-token',
  'keywords': ['freshbooks'],
  'regex': '(?i)[\\w.-]{0,50}?(?:freshbooks)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'gcp-api-key',
  'keywords': ['aiza'],
  'regex': '\\b(AIza[\\w-]{35})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'generic-api-key',
  'keywords': ['access',
               'api',
               'auth',
               'key',
               'credential',
               'creds',
               'passwd',
               'password',
               'secret',
               'token'],
  'regex': '(?i)[\\w.-]{0,50}?(?:access|auth|(?-i:[Aa]pi|API)|credential|creds|key|passw(?:or)?d|secret|token)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([\\w.=-]{10,150}|[a-z0-9][a-z0-9+/]{11,}={0,3})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3.5,
  'secret_group': None},
 {'id': 'github-app-token',
  'keywords': ['ghu_', 'ghs_'],
  'regex': '(?:ghu|ghs)_[0-9a-zA-Z]{36}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'github-fine-grained-pat',
  'keywords': ['github_pat_'],
  'regex': 'github_pat_\\w{82}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'github-oauth',
  'keywords': ['gho_'],
  'regex': 'gho_[0-9a-zA-Z]{36}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'github-pat',
  'keywords': ['ghp_'],
  'regex': 'ghp_[0-9a-zA-Z]{36}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'github-refresh-token',
  'keywords': ['ghr_'],
  'regex': 'ghr_[0-9a-zA-Z]{36}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-cicd-job-token',
  'keywords': ['glcbt-'],
  'regex': 'glcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-deploy-token',
  'keywords': ['gldt-'],
  'regex': 'gldt-[0-9a-zA-Z_\\-]{20}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-feature-flag-client-token',
  'keywords': ['glffct-'],
  'regex': 'glffct-[0-9a-zA-Z_\\-]{20}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-feed-token',
  'keywords': ['glft-'],
  'regex': 'glft-[0-9a-zA-Z_\\-]{20}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-incoming-mail-token',
  'keywords': ['glimt-'],
  'regex': 'glimt-[0-9a-zA-Z_\\-]{25}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-kubernetes-agent-token',
  'keywords': ['glagent-'],
  'regex': 'glagent-[0-9a-zA-Z_\\-]{50}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-oauth-app-secret',
  'keywords': ['gloas-'],
  'regex': 'gloas-[0-9a-zA-Z_\\-]{64}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-pat',
  'keywords': ['glpat-'],
  'regex': 'glpat-[\\w-]{20}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-pat-routable',
  'keywords': ['glpat-'],
  'regex': '\\bglpat-[0-9a-zA-Z_-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b',
  'entropy': 4,
  'secret_group': None},
 {'id': 'gitlab-ptt',
  'keywords': ['glptt-'],
  'regex': 'glptt-[0-9a-f]{40}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-rrt',
  'keywords': ['gr1348941'],
  'regex': 'GR1348941[\\w-]{20}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-runner-authentication-token',
  'keywords': ['glrt-'],
  'regex': 'glrt-[0-9a-zA-Z_\\-]{20}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-runner-authentication-token-routable',
  'keywords': ['glrt-'],
  'regex': '\\bglrt-t\\d_[0-9a-zA-Z_\\-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b',
  'entropy': 4,
  'secret_group': None},
 {'id': 'gitlab-scim-token',
  'keywords': ['glsoat-'],
  'regex': 'glsoat-[0-9a-zA-Z_\\-]{20}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitlab-session-cookie',
  'keywords': ['_gitlab_session='],
  'regex': '_gitlab_session=[0-9a-z]{32}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'gitter-access-token',
  'keywords': ['gitter'],
  'regex': '(?i)[\\w.-]{0,50}?(?:gitter)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'gocardless-api-token',
  'keywords': ['live_', 'gocardless'],
  'regex': '(?i)[\\w.-]{0,50}?(?:gocardless)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(live_[a-z0-9\\-_=]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'grafana-api-key',
  'keywords': ['eyjrijoi'],
  'regex': '(?i)\\b(eyJrIjoi[A-Za-z0-9]{70,400}={0,3})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'grafana-cloud-api-token',
  'keywords': ['glc_'],
  'regex': '(?i)\\b(glc_[A-Za-z0-9+/]{32,400}={0,3})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'grafana-service-account-token',
  'keywords': ['glsa_'],
  'regex': '(?i)\\b(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'harness-api-key',
  'keywords': ['pat.', 'sat.'],
  'regex': '(?:pat|sat)\\.[a-zA-Z0-9_-]{22}\\.[a-zA-Z0-9]{24}\\.[a-zA-Z0-9]{20}',
  'entropy': None,
  'secret_group': None},
 {'id': 'hashicorp-tf-api-token',
  'keywords': ['atlasv1'],
  'regex': '(?i)[a-z0-9]{14}\\.(?-i:atlasv1)\\.[a-z0-9\\-_=]{60,70}',
  'entropy': 3.5,
  'secret_group': None},
 {'id': 'hashicorp-tf-password',
  'keywords': ['administrator_login_password', 'password'],
  'regex': '(?i)[\\w.-]{0,50}?(?:administrator_login_password|password)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}("[a-z0-9=_\\-]{8,20}")(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'heroku-api-key',
  'keywords': ['heroku'],
  'regex': '(?i)[\\w.-]{0,50}?(?:heroku)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'heroku-api-key-v2',
  'keywords': ['hrku-aa'],
  'regex': '\\b((HRKU-AA[0-9a-zA-Z_-]{58}))(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'hubspot-api-key',
  'keywords': ['hubspot'],
  'regex': '(?i)[\\w.-]{0,50}?(?:hubspot)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'huggingface-access-token',
  'keywords': ['hf_'],
  'regex': '\\b(hf_(?i:[a-z]{34}))(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'huggingface-organization-api-token',
  'keywords': ['api_org_'],
  'regex': '\\b(api_org_(?i:[a-z]{34}))(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'infracost-api-token',
  'keywords': ['ico-'],
  'regex': '\\b(ico-[a-zA-Z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'intercom-api-key',
  'keywords': ['intercom'],
  'regex': '(?i)[\\w.-]{0,50}?(?:intercom)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{60})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'intra42-client-secret',
  'keywords': ['intra', 's-s4t2ud-', 's-s4t2af-'],
  'regex': '(?i)\\b(s-s4t2(?:ud|af)-[abcdef0123456789]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'jfrog-api-key',
  'keywords': ['jfrog', 'artifactory', 'bintray', 'xray'],
  'regex': '(?i)[\\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{73})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'jfrog-identity-token',
  'keywords': ['jfrog', 'artifactory', 'bintray', 'xray'],
  'regex': '(?i)[\\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'jwt',
  'keywords': ['ey'],
  'regex': '\\b(ey[a-zA-Z0-9]{17,}\\.ey[a-zA-Z0-9\\/\\\\_-]{17,}\\.(?:[a-zA-Z0-9\\/\\\\_-]{10,}={0,2})?)(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'jwt-base64',
  'keywords': ['zxlk'],
  'regex': '\\bZXlK(?:(?P<alg>aGJHY2lPaU)|(?P<apu>aGNIVWlPaU)|(?P<apv>aGNIWWlPaU)|(?P<aud>aGRXUWlPaU)|(?P<b64>aU5qUWlP)|(?P<crit>amNtbDBJanBi)|(?P<cty>amRIa2lPaU)|(?P<epk>bGNHc2lPbn)|(?P<enc>bGJtTWlPaU)|(?P<jku>cWEzVWlPaU)|(?P<jwk>cWQyc2lPb)|(?P<iss>cGMzTWlPaU)|(?P<iv>cGRpSTZJ)|(?P<kid>cmFXUWlP)|(?P<key_ops>clpYbGZiM0J6SWpwY)|(?P<kty>cmRIa2lPaUp)|(?P<nonce>dWIyNWpaU0k2)|(?P<p2c>d01tTWlP)|(?P<p2s>d01uTWlPaU)|(?P<ppt>d2NIUWlPaU)|(?P<sub>emRXSWlPaU)|(?P<svt>emRuUWlP)|(?P<tag>MFlXY2lPaU)|(?P<typ>MGVYQWlPaUp)|(?P<url>MWNtd2l)|(?P<use>MWMyVWlPaUp)|(?P<ver>MlpYSWlPaU)|(?P<version>MlpYSnphVzl1SWpv)|(?P<x>NElqb2)|(?P<x5c>NE5XTWlP)|(?P<x5t>NE5YUWlPaU)|(?P<x5ts256>NE5YUWpVekkxTmlJNkl)|(?P<x5u>NE5YVWlPaU)|(?P<zip>NmFYQWlPaU))[a-zA-Z0-9\\/\\\\_+\\-\\r\\n]{40,}={0,2}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'kraken-access-token',
  'keywords': ['kraken'],
  'regex': '(?i)[\\w.-]{0,50}?(?:kraken)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9\\/=_\\+\\-]{80,90})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'kubernetes-secret-yaml',
  'keywords': ['secret'],
  'regex': '(?i)(?:\\bkind:[ '
           '\\t]*["\']?\\bsecret\\b["\']?(?s:.){0,200}?\\bdata:(?s:.){0,100}?\\s+([\\w.-]+:(?:[ '
           '\\t]*(?:\\||>[-+]?)\\s+)?[ \\t]*(?:["\']?[a-z0-9+/]{10,}={0,3}["\']?|\\{\\{[ '
           '\\t\\w"|$:=,.-]+}}|""|\'\'))|\\bdata:(?s:.){0,100}?\\s+([\\w.-]+:(?:[ '
           '\\t]*(?:\\||>[-+]?)\\s+)?[ \\t]*(?:["\']?[a-z0-9+/]{10,}={0,3}["\']?|\\{\\{[ '
           '\\t\\w"|$:=,.-]+}}|""|\'\'))(?s:.){0,200}?\\bkind:[ \\t]*["\']?\\bsecret\\b["\']?)',
  'entropy': None,
  'secret_group': None},
 {'id': 'kucoin-access-token',
  'keywords': ['kucoin'],
  'regex': '(?i)[\\w.-]{0,50}?(?:kucoin)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{24})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'kucoin-secret-key',
  'keywords': ['kucoin'],
  'regex': '(?i)[\\w.-]{0,50}?(?:kucoin)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'launchdarkly-access-token',
  'keywords': ['launchdarkly'],
  'regex': '(?i)[\\w.-]{0,50}?(?:launchdarkly)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'linear-api-key',
  'keywords': ['lin_api_'],
  'regex': '(?i)lin_api_[a-z0-9]{40}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'linear-client-secret',
  'keywords': ['linear'],
  'regex': '(?i)[\\w.-]{0,50}?(?:linear)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'linkedin-client-id',
  'keywords': ['linkedin', 'linked_in', 'linked-in'],
  'regex': '(?i)[\\w.-]{0,50}?(?:linked[_-]?in)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{14})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'linkedin-client-secret',
  'keywords': ['linkedin', 'linked_in', 'linked-in'],
  'regex': '(?i)[\\w.-]{0,50}?(?:linked[_-]?in)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'lob-api-key',
  'keywords': ['test_', 'live_'],
  'regex': '(?i)[\\w.-]{0,50}?(?:lob)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}((live|test)_[a-f0-9]{35})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'lob-pub-api-key',
  'keywords': ['test_pub', 'live_pub', '_pub'],
  'regex': '(?i)[\\w.-]{0,50}?(?:lob)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}((test|live)_pub_[a-f0-9]{31})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'looker-client-id',
  'keywords': ['looker'],
  'regex': '(?i)[\\w.-]{0,50}?(?:looker)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'looker-client-secret',
  'keywords': ['looker'],
  'regex': '(?i)[\\w.-]{0,50}?(?:looker)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'mailchimp-api-key',
  'keywords': ['mailchimp'],
  'regex': '(?i)[\\w.-]{0,50}?(?:MailchimpSDK.initialize|mailchimp)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32}-us\\d\\d)(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'mailgun-private-api-token',
  'keywords': ['mailgun'],
  'regex': '(?i)[\\w.-]{0,50}?(?:mailgun)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(key-[a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'mailgun-pub-key',
  'keywords': ['mailgun'],
  'regex': '(?i)[\\w.-]{0,50}?(?:mailgun)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(pubkey-[a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'mailgun-signing-key',
  'keywords': ['mailgun'],
  'regex': '(?i)[\\w.-]{0,50}?(?:mailgun)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'mapbox-api-token',
  'keywords': ['mapbox'],
  'regex': '(?i)[\\w.-]{0,50}?(?:mapbox)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(pk\\.[a-z0-9]{60}\\.[a-z0-9]{22})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'mattermost-access-token',
  'keywords': ['mattermost'],
  'regex': '(?i)[\\w.-]{0,50}?(?:mattermost)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{26})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'maxmind-license-key',
  'keywords': ['_mmk'],
  'regex': '\\b([A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk)(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'messagebird-api-token',
  'keywords': ['messagebird', 'message-bird', 'message_bird'],
  'regex': '(?i)[\\w.-]{0,50}?(?:message[_-]?bird)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{25})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'messagebird-client-id',
  'keywords': ['messagebird', 'message-bird', 'message_bird'],
  'regex': '(?i)[\\w.-]{0,50}?(?:message[_-]?bird)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'microsoft-teams-webhook',
  'keywords': ['webhook.office.com', 'webhookb2', 'incomingwebhook'],
  'regex': 'https://[a-z0-9]+\\.webhook\\.office\\.com/webhookb2/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}@[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}/IncomingWebhook/[a-z0-9]{32}/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}',
  'entropy': None,
  'secret_group': None},
 {'id': 'netlify-access-token',
  'keywords': ['netlify'],
  'regex': '(?i)[\\w.-]{0,50}?(?:netlify)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{40,46})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'new-relic-browser-api-token',
  'keywords': ['nrjs-'],
  'regex': '(?i)[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(NRJS-[a-f0-9]{19})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'new-relic-insert-key',
  'keywords': ['nrii-'],
  'regex': '(?i)[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(NRII-[a-z0-9-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'new-relic-user-api-id',
  'keywords': ['new-relic', 'newrelic', 'new_relic'],
  'regex': '(?i)[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'new-relic-user-api-key',
  'keywords': ['nrak'],
  'regex': '(?i)[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(NRAK-[a-z0-9]{27})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'notion-api-token',
  'keywords': ['ntn_'],
  'regex': '\\b(ntn_[0-9]{11}[A-Za-z0-9]{32}[A-Za-z0-9]{3})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'npm-access-token',
  'keywords': ['npm_'],
  'regex': '(?i)\\b(npm_[a-z0-9]{36})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'nuget-config-password',
  'keywords': ['<add key='],
  'regex': '(?i)<add key=\\"(?:(?:ClearText)?Password)\\"\\s*value=\\"(.{8,})\\"\\s*/>',
  'entropy': 1,
  'secret_group': None},
 {'id': 'nytimes-access-token',
  'keywords': ['nytimes', 'new-york-times', 'newyorktimes'],
  'regex': '(?i)[\\w.-]{0,50}?(?:nytimes|new-york-times,|newyorktimes)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'octopus-deploy-api-key',
  'keywords': ['api-'],
  'regex': '\\b(API-[A-Z0-9]{26})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'okta-access-token',
  'keywords': ['okta'],
  'regex': '[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:(?-i:[Oo]kta|OKTA))(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(00[\\w=\\-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'openai-api-key',
  'keywords': ['t3blbkfj'],
  'regex': '\\b(sk-(?:proj|svcacct|admin)-(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})T3BlbkFJ(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})\\b|sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'openshift-user-token',
  'keywords': ['sha256~'],
  'regex': '\\b(sha256~[\\w-]{43})(?:[^\\w-]|\\z)',
  'entropy': 3.5,
  'secret_group': None},
 {'id': 'perplexity-api-key',
  'keywords': ['pplx-'],
  'regex': '\\b(pplx-[a-zA-Z0-9]{48})(?:[\\x60\'"\\s;]|\\\\[nr]|$|\\b)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'plaid-api-token',
  'keywords': ['plaid'],
  'regex': '(?i)[\\w.-]{0,50}?(?:plaid)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(access-(?:sandbox|development|production)-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'plaid-client-id',
  'keywords': ['plaid'],
  'regex': '(?i)[\\w.-]{0,50}?(?:plaid)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3.5,
  'secret_group': None},
 {'id': 'plaid-secret-key',
  'keywords': ['plaid'],
  'regex': '(?i)[\\w.-]{0,50}?(?:plaid)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3.5,
  'secret_group': None},
 {'id': 'planetscale-api-token',
  'keywords': ['pscale_tkn_'],
  'regex': '(?i)\\b(pscale_tkn_[\\w=\\.-]{32,64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'planetscale-oauth-token',
  'keywords': ['pscale_oauth_'],
  'regex': '\\b(pscale_oauth_[\\w=\\.-]{32,64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'planetscale-password',
  'keywords': ['pscale_pw_'],
  'regex': '(?i)\\b(pscale_pw_[\\w=\\.-]{32,64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'postman-api-token',
  'keywords': ['pmak-'],
  'regex': '(?i)\\b(PMAK-[a-f0-9]{24}\\-[a-f0-9]{34})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'prefect-api-token',
  'keywords': ['pnu_'],
  'regex': '\\b(pnu_[a-zA-Z0-9]{36})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'private-key',
  'keywords': ['-----begin'],
  'regex': '(?i)-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----[\\s\\S-]{64,}?KEY(?: '
           'BLOCK)?-----',
  'entropy': None,
  'secret_group': None},
 {'id': 'privateai-api-token',
  'keywords': ['privateai', 'private_ai', 'private-ai'],
  'regex': '[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:private[_-]?ai)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'pulumi-api-token',
  'keywords': ['pul-'],
  'regex': '\\b(pul-[a-f0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'pypi-upload-token',
  'keywords': ['pypi-ageichlwas5vcmc'],
  'regex': 'pypi-AgEIcHlwaS5vcmc[\\w-]{50,1000}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'rapidapi-access-token',
  'keywords': ['rapidapi'],
  'regex': '(?i)[\\w.-]{0,50}?(?:rapidapi)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{50})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'readme-api-token',
  'keywords': ['rdme_'],
  'regex': '\\b(rdme_[a-z0-9]{70})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'rubygems-api-token',
  'keywords': ['rubygems_'],
  'regex': '\\b(rubygems_[a-f0-9]{48})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'scalingo-api-token',
  'keywords': ['tk-us-'],
  'regex': '\\b(tk-us-[\\w-]{48})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'sendbird-access-id',
  'keywords': ['sendbird'],
  'regex': '(?i)[\\w.-]{0,50}?(?:sendbird)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'sendbird-access-token',
  'keywords': ['sendbird'],
  'regex': '(?i)[\\w.-]{0,50}?(?:sendbird)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'sendgrid-api-token',
  'keywords': ['sg.'],
  'regex': '(?i)\\b(SG\\.[a-z0-9=_\\-\\.]{66})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'sendinblue-api-token',
  'keywords': ['xkeysib-'],
  'regex': '(?i)\\b(xkeysib-[a-f0-9]{64}\\-[a-z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'sentry-access-token',
  'keywords': ['sentry'],
  'regex': '(?i)[\\w.-]{0,50}?(?:sentry)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'sentry-org-token',
  'keywords': ['sntrys_eyjpyxqio'],
  'regex': '\\bsntrys_eyJpYXQiO[a-zA-Z0-9+/]{10,200}(?:LCJyZWdpb25fdXJs|InJlZ2lvbl91cmwi|cmVnaW9uX3VybCI6)[a-zA-Z0-9+/]{10,200}={0,2}_[a-zA-Z0-9+/]{43}(?:[^a-zA-Z0-9+/]|\\z)',
  'entropy': 4.5,
  'secret_group': None},
 {'id': 'sentry-user-token',
  'keywords': ['sntryu_'],
  'regex': '\\b(sntryu_[a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3.5,
  'secret_group': None},
 {'id': 'settlemint-application-access-token',
  'keywords': ['sm_aat'],
  'regex': '\\b(sm_aat_[a-zA-Z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'settlemint-personal-access-token',
  'keywords': ['sm_pat'],
  'regex': '\\b(sm_pat_[a-zA-Z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'settlemint-service-access-token',
  'keywords': ['sm_sat'],
  'regex': '\\b(sm_sat_[a-zA-Z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'shippo-api-token',
  'keywords': ['shippo_'],
  'regex': '\\b(shippo_(?:live|test)_[a-fA-F0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'shopify-access-token',
  'keywords': ['shpat_'],
  'regex': 'shpat_[a-fA-F0-9]{32}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'shopify-custom-access-token',
  'keywords': ['shpca_'],
  'regex': 'shpca_[a-fA-F0-9]{32}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'shopify-private-app-access-token',
  'keywords': ['shppa_'],
  'regex': 'shppa_[a-fA-F0-9]{32}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'shopify-shared-secret',
  'keywords': ['shpss_'],
  'regex': 'shpss_[a-fA-F0-9]{32}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'sidekiq-secret',
  'keywords': ['bundle_enterprise__contribsys__com', 'bundle_gems__contribsys__com'],
  'regex': '(?i)[\\w.-]{0,50}?(?:BUNDLE_ENTERPRISE__CONTRIBSYS__COM|BUNDLE_GEMS__CONTRIBSYS__COM)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{8}:[a-f0-9]{8})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'sidekiq-sensitive-url',
  'keywords': ['gems.contribsys.com', 'enterprise.contribsys.com'],
  'regex': '(?i)\\bhttps?://([a-f0-9]{8}:[a-f0-9]{8})@(?:gems.contribsys.com|enterprise.contribsys.com)(?:[\\/|\\#|\\?|:]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'slack-app-token',
  'keywords': ['xapp'],
  'regex': '(?i)xapp-\\d-[A-Z0-9]+-\\d+-[a-z0-9]+',
  'entropy': 2,
  'secret_group': None},
 {'id': 'slack-bot-token',
  'keywords': ['xoxb'],
  'regex': 'xoxb-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*',
  'entropy': 3,
  'secret_group': None},
 {'id': 'slack-config-access-token',
  'keywords': ['xoxe.xoxb-', 'xoxe.xoxp-'],
  'regex': '(?i)xoxe.xox[bp]-\\d-[A-Z0-9]{163,166}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'slack-config-refresh-token',
  'keywords': ['xoxe-'],
  'regex': '(?i)xoxe-\\d-[A-Z0-9]{146}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'slack-legacy-bot-token',
  'keywords': ['xoxb'],
  'regex': 'xoxb-[0-9]{8,14}-[a-zA-Z0-9]{18,26}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'slack-legacy-token',
  'keywords': ['xoxo', 'xoxs'],
  'regex': 'xox[os]-\\d+-\\d+-\\d+-[a-fA-F\\d]+',
  'entropy': 2,
  'secret_group': None},
 {'id': 'slack-legacy-workspace-token',
  'keywords': ['xoxa', 'xoxr'],
  'regex': 'xox[ar]-(?:\\d-)?[0-9a-zA-Z]{8,48}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'slack-user-token',
  'keywords': ['xoxp-', 'xoxe-'],
  'regex': 'xox[pe](?:-[0-9]{10,13}){3}-[a-zA-Z0-9-]{28,34}',
  'entropy': 2,
  'secret_group': None},
 {'id': 'slack-webhook-url',
  'keywords': ['hooks.slack.com'],
  'regex': '(?:https?://)?hooks.slack.com/(?:services|workflows|triggers)/[A-Za-z0-9+/]{43,56}',
  'entropy': None,
  'secret_group': None},
 {'id': 'snyk-api-token',
  'keywords': ['snyk'],
  'regex': '(?i)[\\w.-]{0,50}?(?:snyk[_.-]?(?:(?:api|oauth)[_.-]?)?(?:key|token))(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'sonar-api-token',
  'keywords': ['sonar'],
  'regex': '(?i)[\\w.-]{0,50}?(?:sonar[_.-]?(login|token))(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}((?:squ_|sqp_|sqa_)?[a-z0-9=_\\-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': 2},
 {'id': 'sourcegraph-access-token',
  'keywords': ['sgp_', 'sourcegraph'],
  'regex': '(?i)\\b(\\b(sgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40}|sgp_[a-fA-F0-9]{40}|[a-fA-F0-9]{40})\\b)(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'square-access-token',
  'keywords': ['sq0atp-', 'eaaa'],
  'regex': '\\b((?:EAAA|sq0atp-)[\\w-]{22,60})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'squarespace-access-token',
  'keywords': ['squarespace'],
  'regex': '(?i)[\\w.-]{0,50}?(?:squarespace)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'stripe-access-token',
  'keywords': ['sk_test', 'sk_live', 'sk_prod', 'rk_test', 'rk_live', 'rk_prod'],
  'regex': '\\b((?:sk|rk)_(?:test|live|prod)_[a-zA-Z0-9]{10,99})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 2,
  'secret_group': None},
 {'id': 'sumologic-access-id',
  'keywords': ['sumo'],
  'regex': '[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:(?-i:[Ss]umo|SUMO))(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(su[a-zA-Z0-9]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'sumologic-access-token',
  'keywords': ['sumo'],
  'regex': '(?i)[\\w.-]{0,50}?(?:(?-i:[Ss]umo|SUMO))(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3,
  'secret_group': None},
 {'id': 'telegram-bot-api-token',
  'keywords': ['telegr'],
  'regex': '(?i)[\\w.-]{0,50}?(?:telegr)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9]{5,16}:(?-i:A)[a-z0-9_\\-]{34})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'travisci-access-token',
  'keywords': ['travis'],
  'regex': '(?i)[\\w.-]{0,50}?(?:travis)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{22})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'twilio-api-key',
  'keywords': ['sk'],
  'regex': 'SK[0-9a-fA-F]{32}',
  'entropy': 3,
  'secret_group': None},
 {'id': 'twitch-api-token',
  'keywords': ['twitch'],
  'regex': '(?i)[\\w.-]{0,50}?(?:twitch)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'twitter-access-secret',
  'keywords': ['twitter'],
  'regex': '(?i)[\\w.-]{0,50}?(?:twitter)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{45})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'twitter-access-token',
  'keywords': ['twitter'],
  'regex': '(?i)[\\w.-]{0,50}?(?:twitter)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9]{15,25}-[a-zA-Z0-9]{20,40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'twitter-api-key',
  'keywords': ['twitter'],
  'regex': '(?i)[\\w.-]{0,50}?(?:twitter)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{25})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'twitter-api-secret',
  'keywords': ['twitter'],
  'regex': '(?i)[\\w.-]{0,50}?(?:twitter)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{50})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'twitter-bearer-token',
  'keywords': ['twitter'],
  'regex': '(?i)[\\w.-]{0,50}?(?:twitter)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(A{22}[a-zA-Z0-9%]{80,100})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'typeform-api-token',
  'keywords': ['tfp_'],
  'regex': '(?i)[\\w.-]{0,50}?(?:typeform)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(tfp_[a-z0-9\\-_\\.=]{59})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'vault-batch-token',
  'keywords': ['hvb.'],
  'regex': '\\b(hvb\\.[\\w-]{138,300})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 4,
  'secret_group': None},
 {'id': 'vault-service-token',
  'keywords': ['hvs.', 's.'],
  'regex': '\\b((?:hvs\\.[\\w-]{90,120}|s\\.(?i:[a-z0-9]{24})))(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': 3.5,
  'secret_group': None},
 {'id': 'yandex-access-token',
  'keywords': ['yandex'],
  'regex': '(?i)[\\w.-]{0,50}?(?:yandex)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(t1\\.[A-Z0-9a-z_-]+[=]{0,2}\\.[A-Z0-9a-z_-]{86}[=]{0,2})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'yandex-api-key',
  'keywords': ['yandex'],
  'regex': '(?i)[\\w.-]{0,50}?(?:yandex)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(AQVN[A-Za-z0-9_\\-]{35,38})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'yandex-aws-access-token',
  'keywords': ['yandex'],
  'regex': '(?i)[\\w.-]{0,50}?(?:yandex)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(YC[a-zA-Z0-9_\\-]{38})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None},
 {'id': 'zendesk-secret-key',
  'keywords': ['zendesk'],
  'regex': '(?i)[\\w.-]{0,50}?(?:zendesk)(?:[ '
           '\\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)',
  'entropy': None,
  'secret_group': None}]

STOPWORDS = ['014df517-39d1-4453-b7b3-9930c563627c', 'abcdefghijklmnopqrstuvwxyz']

ALLOW_REGEXES = ['(?i)^true|false|null$',
 '^(?i:a+|b+|c+|d+|e+|f+|g+|h+|i+|j+|k+|l+|m+|n+|o+|p+|q+|r+|s+|t+|u+|v+|w+|x+|y+|z+|\\*+|\\.+)$',
 '^\\$(?:\\d+|{\\d+})$',
 '^\\$(?:[A-Z_]+|[a-z_]+)$',
 '^\\${(?:[A-Z_]+|[a-z_]+)}$',
 '^\\{\\{[ \\t]*[\\w ().|]+[ \\t]*}}$',
 '^\\$\\{\\{[ \\t]*(?:(?:env|github|secrets|vars)(?:\\.[A-Za-z]\\w+)+[\\w '
 '"\'&./=|]*)[ \\t]*}}$',
 '^%(?:[A-Z_]+|[a-z_]+)%$',
 '^%[+\\-# 0]?[bcdeEfFgGoOpqstTUvxX]$',
 '^\\{\\d{0,2}}$',
 '^@(?:[A-Z_]+|[a-z_]+)@$',
 '(?i)^/Users/[a-z0-9]+/[\\w .-/]+$',
 '^/(?:bin|etc|home|opt|tmp|usr|var)/[\\w ./-]+$']
